/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "var(--inverse-surface)",
        "primary": "var(--primary)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "error-container": "var(--error-container)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "tertiary-container": "var(--tertiary-container)",
        "on-error": "var(--on-error)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "surface-tint": "var(--surface-tint)",
        "surface-container-low": "var(--surface-container-low)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-background": "var(--on-background)",
        "on-surface": "var(--on-surface)",
        "on-tertiary": "var(--on-tertiary)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-surface-variant": "var(--on-surface-variant)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "inverse-primary": "var(--inverse-primary)",
        "primary-fixed": "var(--primary-fixed)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "surface": "var(--surface)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "tertiary": "var(--tertiary)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "outline": "var(--outline)",
        "error": "var(--error)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-primary": "var(--on-primary)",
        "surface-variant": "var(--surface-variant)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-error-container": "var(--on-error-container)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "secondary": "var(--secondary)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-bright": "var(--surface-bright)",
        "primary-container": "var(--primary-container)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-secondary": "var(--on-secondary)",
        "surface-dim": "var(--surface-dim)",
        "surface-container-highest": "var(--surface-container-highest)",
        "outline-variant": "var(--outline-variant)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-primary-container": "var(--on-primary-container)",
        "secondary-container": "var(--secondary-container)",
        "surface-container": "var(--surface-container)",
        "background": "var(--background)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "container-max": "1280px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "section-v-space-mobile": "64px",
        "gutter": "24px",
        "section-v-space": "120px"
      },
      fontSize: {
        "headline-section-mobile": ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-subsection": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-hero": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-large": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "meta-info": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-section": ["36px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-base": ["16px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
