/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#293040",
        "primary": "#004ac6",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#ffede6",
        "on-secondary-fixed-variant": "#3e4755",
        "tertiary-container": "#bc4800",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#121c28",
        "surface-tint": "#0053db",
        "surface-container-low": "#f1f3ff",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-background": "#141b2b",
        "on-surface": "#141b2b",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#00174b",
        "on-surface-variant": "#434655",
        "tertiary-fixed": "#ffdbcd",
        "inverse-primary": "#b4c5ff",
        "primary-fixed": "#dbe1ff",
        "inverse-on-surface": "#edf0ff",
        "surface": "#f9f9ff",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary": "#943700",
        "secondary-fixed-dim": "#bdc7d8",
        "outline": "#737686",
        "error": "#ba1a1a",
        "secondary-fixed": "#d9e3f4",
        "on-primary": "#ffffff",
        "surface-variant": "#dce2f7",
        "on-primary-fixed-variant": "#003ea8",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#360f00",
        "secondary": "#555f6d",
        "surface-container-high": "#e1e8fd",
        "surface-bright": "#f9f9ff",
        "primary-container": "#2563eb",
        "tertiary-fixed-dim": "#ffb596",
        "on-secondary": "#ffffff",
        "surface-dim": "#d3daef",
        "surface-container-highest": "#dce2f7",
        "outline-variant": "#c3c6d7",
        "on-secondary-container": "#596372",
        "on-primary-container": "#eeefff",
        "secondary-container": "#d6e0f1",
        "surface-container": "#e9edff",
        "background": "#f9f9ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "container-max": "1280px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "section-v-space-mobile": "64px",
        "gutter": "24px",
        "section-v-space": "120px"
      },
      fontSize: {
        "headline-section-mobile": ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-subsection": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-hero": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-large": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "meta-info": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-section": ["36px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-base": ["16px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
